name: RELEASE

on:
  repository_dispatch:
    types: [make_release]
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: semantic-config-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            semantic-config-

      - name: Build Release
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISHING_TOKEN }}
        run: |
          yarn install
          yarn release
